[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
ethereum = "https://ethereum-rpc.publicnode.com"
